# Generated by Django 3.1.7 on 2021-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyBasicData',
            fields=[
                ('id', models.CharField(help_text="user's id in spotify database", max_length=64, primary_key=True, serialize=False, unique=True)),
                ('uri', models.CharField(help_text="user's uri in Spotify. can be construct with id", max_length=64)),
                ('display_name', models.CharField(help_text="user's display name in spotify", max_length=64, null=True)),
                ('image_url', models.TextField(help_text="user's image url in spotify", max_length=1024, null=True)),
                ('external_url', models.TextField(help_text="user's first external url in spotify", max_length=1024, null=True)),
                ('product', models.CharField(help_text='kind of product owned by this user in spotify', max_length=32)),
                ('access_token', models.CharField(help_text="user's actual token", max_length=255)),
                ('refresh_token', models.CharField(help_text="user's token to exchange when access_token is expired", max_length=255)),
                ('access_token_expires_at', models.DateTimeField(help_text='maximum datetime to use the access_token')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
