# Generated by Django 3.1.7 on 2021-03-03 22:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import room.snippets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('host', models.OneToOneField(help_text='who created the room', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.users')),
                ('code', models.CharField(default=room.snippets.generate_unique_code, help_text='public room identifier', max_length=16, unique=True)),
                ('guests_can_pause', models.BooleanField(default=False, help_text='allow guests to pause a room')),
                ('votes_to_skip', models.PositiveSmallIntegerField(default=1, help_text='votes to reach so the song will be skipped', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('current_votes', models.PositiveSmallIntegerField(default=0, help_text='total of votes for the current song', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
