# Generated by Django 3.1.7 on 2021-03-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_playback',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='song_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
