# Generated by Django 3.1.7 on 2021-03-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20210321_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='track_id',
            new_name='last_known_track_id',
        ),
    ]
