# Generated by Django 3.1.7 on 2021-03-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0002_auto_20210326_2257'),
        ('user', '0001_initial'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='room',
            field=models.ForeignKey(default=None, help_text='the room which the user is joined', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='room.rooms'),
        ),
        migrations.AddField(
            model_name='users',
            name='spotify_basic_data',
            field=models.ForeignKey(help_text='instance from spotify.SpotifyBasicData', null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify.spotifybasicdata'),
        ),
    ]
